Repository GSG-G10/news-website-team4, pull requests merged in 2021-07, with the labels that each got.

#10 Nav Bar Section
  images/download.webp
  post/post.html
  style/post.css
Labels: awaiting-review‏

#20 Homejo
  images/header_01.jpg
  images/header_02.jpg
  images/header_03.jpg
  images/header_04.jpg
  images/video_1.webp
  images/video_2.webp
  images/video_3.webp
  images/video_4.jpg
  index.html
  style/style_home.css
Labels: Done, awaiting-review‏

#14 Art culture section
  images/artandculture.webp
  images/artandculture2.webp
  images/artandculture3.webp
  images/artandculture_ad.webp
  index.html
  style/style_home.css
Labels: awaiting-review‏

#16 Science update
  images/science.webp
  images/science2.webp
  images/science3.webp
  images/science4.webp
  index.html
  style/style_home.css
Labels: awaiting-review‏

#18 Sport section
  images/science.jpg
  images/science.webp
  images/science2.jpg
  images/science2.webp
  images/science3.jpg
  images/science3.webp
  images/science4.png
  images/science4.webp
  images/sport.jpg
  images/sport2.jpeg
  images/sport3.jpg
  images/sport4.jpg
  index.html
  style/style_home.css
Labels: awaiting-review‏

#21 Subscribe section
  index.html
  style/style_home.css
Labels: awaiting-review‏

#23 edit_html_conflict_problem
  index.html
Labels: awaiting-review‏

#24 Post content
  .vscode/settings.json
  images/facebook.webp
  images/pinterest.webp
  images/post-first.webp
  images/post-second.webp
  images/twitter.webp
  images/whatsapp.webp
  post/post.html
Labels: inProgress

#30 Most related news
  index.html
  style/style_home.css
Labels: awaiting-review‏

#27 Creat footer
  index.html
  post/post.html
  style/common.css
  style/post.css
  style/style_home.css
Labels: awaiting-review‏

#33 Add images for most important and most viewed sections
  images/most_news.webp
  images/most_news2.webp
  images/most_news3.webp
  images/most_news4.webp
  images/most_news5.webp
Labels: awaiting-review‏

#11 Adding form
  post/post.html
  style/post.css
  style/style_home.css
Labels: awaiting-review‏

#34 Add the style for the post content
  post/post.html
  style/post.css
Labels: awaiting-review‏

#47 last update done
  images/slid1.jpg
  images/slid2.jpg
  images/slid3.jpg
  images/slid4.jpg
  images/slid5.jpg
  images/slid6.png
  images/slid7.jpg
  index.html
  js/app.js
  style/pop.css
  style/style_home.css
Labels: awaiting-review‏

#45 Menu List
  post/post.html
  post/post.js
  style/post.css
Labels: awaiting-review‏

#36 Add Navbar to Home Page
  index.html
  style/style_home.css
Labels: awaiting-review‏

#51 fix important and most news section
  index.html
  style/style_home.css
Labels: awaiting-review‏

#50 Readme File
  README.md
  index.html
  style/style_home.css
Labels: awaiting-review‏

#53 fix logo and some links
  index.html
  style/style_home.css
Labels: awaiting-review‏

#54 fix related news problems
  index.html
  style/style_home.css
Labels: awaiting-review‏

#67 fix links
  index.html
  js/app.js
  post/post.html
  style/style_home.css
Labels: awaiting-review‏

#68 fix link post
  js/app.js
Labels: awaiting-review‏
